services:
  postgres:
    image: postgres:16
    container_name: hospital-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hospital_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hospital-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hospital-rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - hospital-network

volumes:
  postgres-data:

networks:
  hospital-network:
    driver: bridge
